config/routes.rb
Goscience::Application.routes.draw do
  resources :seeds

  root to: "seeds#new"
end

app/models/seed.rb
class Seed < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/seeds_controller.rb
class SeedsController < ApplicationController
  before_action :set_seed, only: [:show, :edit, :update, :destroy]

  # GET /seeds
  # GET /seeds.json
  def index
    @seeds = Seed.all
  end

  # GET /seeds/1
  # GET /seeds/1.json
  def show
  end

  # GET /seeds/new
  def new
    @seed = Seed.new
  end

  # GET /seeds/1/edit
  def edit
  end

  # POST /seeds
  # POST /seeds.json
  def create
    @seed = Seed.new(seed_params)

    respond_to do |format|
      if @seed.save
        format.html { redirect_to @seed, notice: 'Seed was successfully created.' }
        format.json { render action: 'show', status: :created, location: @seed }
      else
        format.html { render action: 'new' }
        format.json { render json: @seed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seeds/1
  # PATCH/PUT /seeds/1.json
  def update
    respond_to do |format|
      if @seed.update(seed_params)
        format.html { redirect_to @seed, notice: 'Seed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @seed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seeds/1
  # DELETE /seeds/1.json
  def destroy
    @seed.destroy
    respond_to do |format|
      format.html { redirect_to seeds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seed
      @seed = Seed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seed_params
      params.require(:seed).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seeds_helper.rb
module SeedsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goscience</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">GoScience.cc</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    
    
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">How It Works</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Seeds</a></li>
          <li><a href="#">Projects</a></li>
          <li><a href="#">Users</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
<div class="container">

<%= yield %>
</div>
</body>
</html>

app/views/seeds/_form.html.erb
<%= form_for(@seed) do |f| %>
  <% if @seed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seed.errors.count, "error") %> prohibited this seed from being saved:</h2>

      <ul>
      <% @seed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form class="form-inline" role="form">
  <div class="form-group">
    <%= f.label :title, :class=> "sr-only" %><br>
    <%= f.text_field :title, :class=>"form-control", :placeholder => "I Think I know Why the Apple Fell from the Tree", :style => "height: 60px;" %> 
  </div>
  <div>
    <%= f.submit :class => "btn btn-default" %>
  </div>
</div>
</form>
<% end %>

app/views/seeds/edit.html.erb
<h1>Editing seed</h1>

<%= render 'form' %>

<%= link_to 'Show', @seed %> |
<%= link_to 'Back', seeds_path %>

app/views/seeds/index.html.erb
<h1>Listing seeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @seeds.each do |seed| %>
      <tr>
        <td><%= seed.title %></td>
        <td><%= seed.description %></td>
        <td><%= link_to 'Show', seed %></td>
        <td><%= link_to 'Edit', edit_seed_path(seed) %></td>
        <td><%= link_to 'Destroy', seed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seed', new_seed_path %>

app/views/seeds/new.html.erb
<div class="seeds"> <%= image_tag "chemcat.jpg", :style => "width: 350px", :class => "mrcat" %> </div>
	
	


<div class="frontseed">
	<h1>What's Your Idea ? </h1>
	<%= render 'form' %>
</div>

app/views/seeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @seed.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @seed.description %>
</p>

<%= link_to 'Edit', edit_seed_path(@seed) %> |
<%= link_to 'Back', seeds_path %>